Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

AllCops:
  TargetRubyVersion: 2.3
  Excludes:
    - 'client/**/*'
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'app/controllers/api/v1/overrides/passwords_controller.rb'

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FrozenStringLiteralComment:
  EnforcedStyle: always